// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LinqExpressions.Entity
{
    public partial class Table1
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string T1 { get; set; }
        [StringLength(50)]
        public string T2 { get; set; }
        [StringLength(50)]
        public string T3 { get; set; }
        [StringLength(50)]
        public string T4 { get; set; }
    }
}