// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorDemo.Models;

public partial class Company
{
    [Key]
    public Guid CompanyId { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [StringLength(50)]
    public string ModifyUser { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifyTime { get; set; }
}