// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFDemo.Models
{
    public partial class User
    {
        [Key]
        public Guid UserId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public Address Address { get; set; }
    }
}